#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

$app = new ElfSundae\Console\Application;

$app->command('basic {username}', function ($username) {
    $this->comment(title_case($username));
}, 'The `basic` command description');

$app->setDefaultCommand('basic', true);

$app->run();
