#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use ElfSundae\Console\Application;

Application::runCommand(
    'Basic Tool',
    '1.0',
    Application::command('basic {username=Elf Sundae}', function ($username) {
        $username = title_case($username);

        $this->line("Hello, <comment>$username</comment>!");
    })->describe('Command description')
);
