#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

class ExampleCommand extends Illuminate\Console\Command
{
    protected $signature = 'example
        {--f|foo=bar : The "foo" option description}';

    protected $description = 'Example command description';

    public function handle()
    {
        $this->comment($this->option('foo'));
    }
}

(new ElfSundae\Console\Application)
    ->add($command = new ExampleCommand)
    ->getApplication()
    ->setDefaultCommand($command->getName(), true)
    ->run();
